export const Colors = {
  light: {
    primary: "#ED225D",
    cta: "#FF69B4",
    onPrimary: "#FFFFFF",
    primaryContainer: "#FFD9E4",
    onPrimaryContainer: "#5A001C",
    primaryFixedDim: "#FFB2BB",
    secondary: "#7E5260",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#FFD9E4",
    onSecondaryContainer: "#2E1522",
    tertiary: "#7E5674",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#FFD8F0",
    onTertiaryContainer: "#311F2E",
    surface: "#FFFFFF",
    onSurface: "#1C1B1F",
    surfaceDim: "#F3F4F6",
    surfaceBright: "#FFFFFF",
    surfaceContainer: "#F5F5F5",
    surfaceContainerLow: "#FAFAFA",
    surfaceContainerHigh: "#EFEFEF",
    surfaceContainerHighest: "#E5E5E5",
    surfaceContainerLowest: "#FFFFFF",
    onSurfaceVariant: "#49454F",
    outline: "#79747E",
    outlineVariant: "#C4C4C6",
    textSecondary: "#6B7280",
    inverseSurface: "#313033",
    inverseOnSurface: "#F4EFF4",
    inversePrimary: "#FFB2BB",
    scrim: "#000000",
    error: "#BA1A1A",
    errorContainer: "#FFDAD6",
    onError: "#FFFFFF",
    onErrorContainer: "#410002",
    success: "#2E7D32",
    onSuccess: "#FFFFFF",
    successContainer: "#C8E6C9",
    onSuccessContainer: "#0A3D0E",
  },
  dark: {
    primary: "#ED225D",
    cta: "#FF69B4",
    onPrimary: "#FFFFFF",
    primaryContainer: "#FF4F75",
    onPrimaryContainer: "#5A001C",
    primaryFixedDim: "#FFB2BB",
    secondary: "#E4BDC0",
    onSecondary: "#452936",
    secondaryContainer: "#633F4C",
    onSecondaryContainer: "#FFD9E4",
    tertiary: "#E2BBD6",
    onTertiary: "#483545",
    tertiaryContainer: "#604B5C",
    onTertiaryContainer: "#FFD8F0",
    surface: "#121317",
    onSurface: "#E3E2E7",
    surfaceDim: "#121317",
    surfaceBright: "#38393D",
    surfaceContainer: "#1E1F23",
    surfaceContainerLow: "#1A1B1F",
    surfaceContainerHigh: "#292A2E",
    surfaceContainerHighest: "#343539",
    surfaceContainerLowest: "#0D0E12",
    onSurfaceVariant: "#E4BDC0",
    outline: "#938F99",
    outlineVariant: "#49454F",
    textSecondary: "#9CA3AF",
    inverseSurface: "#E3E2E7",
    inverseOnSurface: "#2F3034",
    inversePrimary: "#BE185D",
    scrim: "#000000",
    error: "#FFB4AB",
    errorContainer: "#93000A",
    onError: "#690005",
    onErrorContainer: "#FFDAD6",
    success: "#7CD97C",
    onSuccess: "#082E0A",
    successContainer: "#1E4A1F",
    onSuccessContainer: "#B8F2B6",
  },
} as const;

// Dedicated palette for the custom keyboards, kept separate from the flat
// theme record so consumers that treat Colors[scheme] as Record<string,string>
// stay type-safe. Light values invert the dark design; the blue accent is
// shared by both modes.
export const KeyboardColors = {
  light: {
    background: "#F5F5F5",
    keyCap: "#E0E0E0",
    keyCapPressed: "#CFCFCF",
    text: "#1A1A1A",
    textMuted: "#6B7280",
    accent: "#2B82F6",
    toolbarKey: "#E0E0E0",
    toolbarKeyPressed: "#CFCFCF",
  },
  dark: {
    background: "#121212",
    keyCap: "#2A2A2E",
    keyCapPressed: "#3A3A3E",
    text: "#FFFFFF",
    textMuted: "#9CA3AF",
    accent: "#2B82F6",
    toolbarKey: "#2A2A2E",
    toolbarKeyPressed: "#3A3A3E",
  },
} as const;

export type KeyboardColorScheme = keyof typeof KeyboardColors;

export type ThemeColorScheme = keyof typeof Colors;
