export const STORAGE_KEYS = {
  completedLessons: "completedLessons",
  completedCourses: "completedCourses",
  onboardingData: "onboardingData",
  hasCompletedOnboarding: "hasCompletedOnboarding",
  completionEvents: "completion_events",
  achievementsUnlocked: "achievements_unlocked",
  achievementsUnlockedAt: "achievements_unlocked_at",
  userColorScheme: "userColorScheme",
  streakCount: "streak_count",
  streakLastVisit: "streak_last_visit",
  streakLongest: "streak_longest",
  streakToastPending: "streak_toast_pending",
  didYouKnowLastShown: "did_you_know_last_shown",
  settingCodeFontSize: "setting_codeFontSize",
  settingCtaColor: "setting_ctaColor",
  settingDisableSystemKeyboard: "setting_disableSystemKeyboard",
  settingEditorTheme: "setting_editorTheme",
  settingKeyboardHeight: "setting_keyboardHeight",
  settingShowStatusBar: "setting_showStatusBar",
  settingWordWrap: "setting_wordWrap",
  settingShowDrawerFab: "setting_showDrawerFab",
  settingCodeBackground: "setting_codeBackground",
  settingDailyReminder: "setting_dailyReminder",
  settingNotificationHour: "setting_notificationHour",
  settingNotificationMinute: "setting_notificationMinute",
};
