#!/usr/bin/env node
// Reads all .yaml files in src/data/courses/ and generates matching .ts files.
// Run via: npm run build-courses
import fs from "fs";
import path from "path";
import jsyaml from "js-yaml";

const COURSES_DIR = path.resolve("src/data/courses");

function slugToVarName(slug) {
  return slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "Course";
}

const yamlFiles = fs
  .readdirSync(COURSES_DIR)
  .filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"));

let count = 0;

for (const file of yamlFiles) {
  const yamlPath = path.join(COURSES_DIR, file);
  const raw = fs.readFileSync(yamlPath, "utf8");
  const data = jsyaml.load(raw);

  if (!data || !data.slug) {
    console.error(`  ✗ ${file}: missing "slug" field, skipping`);
    continue;
  }

  const varName = slugToVarName(data.slug);
  const tsPath = path.join(COURSES_DIR, data.slug + ".ts");

  const jsonStr = JSON.stringify(data, null, 2);
  const tsContent =
    `// AUTO-GENERATED by scripts/build-courses.mjs — do not edit manually.\n` +
    `// Source: ${file}\n` +
    `import type { Course } from "../../data/types";\n` +
    `export const ${varName}: Course = ${jsonStr};\n`;

  fs.writeFileSync(tsPath, tsContent, "utf8");
  console.log(`  ✓ ${file} → ${data.slug}.ts (${varName})`);
  count++;
}

console.log(`\nBuilt ${count} course file(s).`);
